services:
  mongo:
    image: mongo:6
    container_name: ai-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-backend
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env:ro
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: /api
    container_name: ai-frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  mongo_data:
